# Example configuration
# Move this file to your home directory: ~/

# This is an example configuration file for bux-cli
mode: "database" # "database" or "server"
database: "bux.db" # Path to database file
server: "http://localhost:8080" # Server address